[package]
name = "formalize"
version = "0.1.0"
edition = "2021"
authors = ["Nadir Fejzic <nadirfejzo@gmail.com>"]
description = "To be added"
license = "Apache-2.0"

[dependencies]
alemat = "0.7.0"
leptos = { version = "0.5.4", features = ["csr"] }
mathemascii = "0.3.1"
